#  access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzYwMjY4NmJlYjUzNTExNjIwNGM0OSIsImlhdCI6MTcwMjIzMjY4MH0.9BerD2xwYLXW_UJuVq9DL-01pJ26KnxKDN3p5SzrcjI

# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email": "admi2@gmail.com",
#     "password": "Admin@gmailcom"
# }

# GET http://localhost:3000/get-upload-url



# POST  http://localhost:3000/create-blog
# Content-Type: application/json


# {
#     "blog-name": "This is a new blog test"

# }


# POST  http://localhost:3000/signup 
# Content-Type: application/json


# {
#     "fullname" : "john",
#     "email" : "admin1@gmail.com",
#     "password" : "Admin@12gmail.com"
# }


# POST http://localhost:3000/create-blog
# Content-Type:application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzYwMjY4NmJlYjUzNTExNjIwNGM0OSIsImlhdCI6MTcwMjIzMjY4MH0.9BerD2xwYLXW_UJuVq9DL-01pJ26KnxKDN3p5SzrcjI

# {
#     "title" : "test title",
#     "des" : "this is a des",
#     "banner" : "https://example.com/image-url",    
#     "content": {
#         "blocks" : [ 1,2 ]
#     },
#     "tags" : ["tag1", "tag2"]
# }


GET http://localhost:3000/latest-blogs

